version: "3"
services:
  nginx:
    image: nginx:1.13
    container_name: webservice
    volumes:
      - "./code-php:/usr/share/nginx/html"
      - "./nginx/sites-enabled/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - devops-network

  php:
    build:
      context: .
    container_name: app-php
    volumes:
      - "./code-php:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - devops-network

networks:
    devops-network:
      driver: bridge